modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.neoi]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.neoi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[mods]]
    modId="neoi"
    version="1.0.0"
    displayName="Not Enough Object Info"
    description="Displays detailed information about blocks, items, and entities."
